name: CI/CD for nodejs app

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

# Define the jobs to be executed
jobs:
  # Deploy job
  Deploy:
    # Use a self-hosted runner for deployment
    runs-on: self-hosted
    # Steps to be executed in the Deploy job
    steps:
      # Login to DockerHub using secrets for credentials
      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      # Create .env file
      - name: Create .env file
        run: echo "${{ secrets.PROD_ENV_FILE }}" > .env
      # Pull the latest Docker image from DockerHub
      - name: Pull the Docker Image
        run: docker pull cjscrypt/lightening_trade_bot:latest 
      # Delete the old container if it exists
      - name: Delete Old Container
        run: |
          if [ "$(docker ps -q -f name=lightening_trade_bot-Container)" ]; then
            sudo docker rm -f lightening_trade_bot-Container
          fi
      # Run a new container from the pulled image
      - name: Run the Container
        run: docker run --env-file .env -d -p 3000:3000 --name lightening_trade_bot-Container cjscrypt/lightening_trade_bot
      # Remove created .env file after running container
      - name: Clean .env file
        run: rm .env
